In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset= pd.read_csv(r"C:\Churn_Modelling.csv")

In [3]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225       NaN  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   
5          6    15574012       Chu          645     Spain    Male  44.0   
6          7    15592531  Bartlett          619    France    Male  50.0   
7          8    15656148    Obinna          376   Germany     NaN   NaN   
8          9    15792365        He          501    France    Male  44.0   
9         10    15592389        H?          684    France    Male  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [4]:
dataset.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [5]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [6]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
dataset["Geography"].fillna(dataset["Geography"].mode()[0],inplace=True)
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)
dataset["Age"].fillna(dataset["Age"].mean(),inplace=True)

In [8]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [9]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          225    France  Female   
2             3    15619304            Onio          629    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          619    France    Male   
7             8    15656148          Obinna          376   Germany    Male   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [10]:
dataset["Geography"].mode()[0]

'France'

In [11]:
dataset["Gender"].mode()[0]

'Male'

In [12]:
dataset["Age"].mean()

38.924392439243924

In [13]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [14]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

integer encoding-label encoding
binaryv encoding-column transform

In [15]:
dataset["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [16]:
dataset["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Geography"]=le.fit_transform(dataset["Geography"])
dataset["Gender"]=le.fit_transform(dataset["Gender"])

In [18]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender        Age  \
0          1    15634602  Hargrave          619          0       0  42.000000   
1          2    15647311      Hill          225          0       0  41.000000   
2          3    15619304      Onio          629          0       0  42.000000   
3          4    15701354      Boni          699          0       0  39.000000   
4          5    15737888  Mitchell          850          2       0  43.000000   
5          6    15574012       Chu          645          2       1  44.000000   
6          7    15592531  Bartlett          619          0       1  50.000000   
7          8    15656148    Obinna          376          1       1  38.924392   
8          9    15792365        He          501          0       1  44.000000   
9         10    15592389        H?          684          0       1  43.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [19]:
d=pd.DataFrame([[1,2,3,4],[5,6,7,8],[2,5,6,7],[7,8,9,0]],columns=["a","b","c","d"])

In [20]:
d

a  b  c  d
0  1  2  3  4
1  5  6  7  8
2  2  5  6  7
3  7  8  9  0

In [21]:
d.iloc[:,1:]

b  c  d
0  2  3  4
1  6  7  8
2  5  6  7
3  8  9  0

In [22]:
x=dataset.iloc[:,3:12]

In [23]:
y=dataset.iloc[:,13]

In [24]:
x

CreditScore  Geography  Gender        Age  Tenure    Balance  \
0             619          0       0  42.000000       2       0.00   
1             225          0       0  41.000000       1   83807.86   
2             629          0       0  42.000000       8  159660.80   
3             699          0       0  39.000000       1       0.00   
4             850          2       0  43.000000       2  125510.82   
5             645          2       1  44.000000       8  113755.78   
6             619          0       1  50.000000       7       0.00   
7             376          1       1  38.924392       4  115046.74   
8             501          0       1  44.000000       4  142051.07   
9             684          0       1  43.000000       2  134603.88   
10            528          0       1  31.000000       6  134603.88   
11            497          2       1  24.000000       3       0.00   
12            476          0       0  34.000000      10       0.00   
13            549          0       0  25.000000       5       0.00   
14            635          2       0  35.000000       7       0.00   
15            616          1       1  45.000000       3  143129.41   
16            653          1       1  58.000000       1  132602.88   
17            549          2       0  24.000000       9       0.00   
18            587          2       1  45.000000       6       0.00   
19            726          0       0  24.000000       6       0.00   
20            732          0       1  41.000000       8       0.00   
21            636          2       0  32.000000       8       0.00   
22            510          2       0  38.000000       4       0.00   
23            669          0       1  46.000000       3       0.00   
24            846          0       0  38.000000       5       0.00   
25            577          0       1  25.000000       3       0.00   
26            756          1       1  36.000000       2  136815.64   
27            571          0       1  44.000000       9       0.00   
28            574          1       0  43.000000       3  141349.43   
29            411          0       1  29.000000       0   59697.17   
...           ...        ...     ...        ...     ...        ...   
9970          518          0       1  42.000000       7  151027.05   
9971          833          0       0  34.000000       3  144751.81   
9972          758          0       1  26.000000       4  155739.76   
9973          611          0       1  27.000000       7       0.00   
9974          583          0       1  33.000000       7  122531.86   
9975          610          1       1  50.000000       1  113957.01   
9976          637          0       0  33.000000       7  103377.81   
9977          683          0       0  32.000000       9       0.00   
9978          774          0       1  40.000000       9   93017.47   
9979          677          0       0  58.000000       1   90022.85   
9980          741          2       1  35.000000       6   74371.49   
9981          498          1       1  42.000000       3  152039.70   
9982          655          1       0  46.000000       7  137145.12   
9983          613          0       1  40.000000       4       0.00   
9984          602          1       1  35.000000       7   90602.42   
9985          659          0       1  36.000000       6  123841.49   
9986          673          1       1  47.000000       1  183579.54   
9987          606          2       1  30.000000       8  180307.73   
9988          775          0       1  30.000000       4       0.00   
9989          841          2       1  28.000000       4       0.00   
9990          714          1       1  33.000000       3   35016.60   
9991          597          0       0  53.000000       4   88381.21   
9992          726          2       1  36.000000       2       0.00   
9993          644          0       1  28.000000       7  155060.41   
9994          800          0       0  29.000000       2       0.00   
9995          77

In [25]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [26]:
x1=dataset.iloc[:,3]

In [27]:
x1

0       619
1       225
2       629
3       699
4       850
5       645
6       619
7       376
8       501
9       684
10      528
11      497
12      476
13      549
14      635
15      616
16      653
17      549
18      587
19      726
20      732
21      636
22      510
23      669
24      846
25      577
26      756
27      571
28      574
29      411
       ... 
9970    518
9971    833
9972    758
9973    611
9974    583
9975    610
9976    637
9977    683
9978    774
9979    677
9980    741
9981    498
9982    655
9983    613
9984    602
9985    659
9986    673
9987    606
9988    775
9989    841
9990    714
9991    597
9992    726
9993    644
9994    800
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [28]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender   Age  \
0          1    15634602  Hargrave          619          0       0  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [29]:
x=dataset.iloc[:,3:13].values

In [30]:
y=dataset.iloc[:,13].values

In [31]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [32]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [33]:
x.shape

(10000, 10)

In [34]:
y.shape

(10000,)

In [35]:
from sklearn.preprocessing import OneHotEncoder#creates columns based on categories of textual data
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,2])],remainder="passthrough")#add columns to first
x=ct.fit_transform(x)

C:\Users\JahnaviP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [36]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [37]:
x[1,:]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 2.2500000e+02, 4.1000000e+01, 1.0000000e+00,
       8.3807860e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.1254258e+05])

In [38]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender   Age  \
0          1    15634602  Hargrave          619          0       0  42.0   
1          2    15647311      Hill          225          0       0  41.0   
2          3    15619304      Onio          629          0       0  42.0   
3          4    15701354      Boni          699          0       0  39.0   
4          5    15737888  Mitchell          850          2       0  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [39]:
x.shape

(10000, 13)

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [41]:
x_train.shape

(8000, 13)

In [42]:
x_test.shape

(2000, 13)

In [43]:
y_train.shape

(8000,)

In [44]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [45]:
y_test[0]

0

In [46]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
y_test.shape

(2000,)

In [48]:
x1=[1,2,4,5,7,8,9]
y1=[0,1,0,1,0,1,1]

In [49]:
for i in range(5):
    x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.2)
    print("values without random state is",x1_train)

values without random state is [8, 9, 5, 7, 2]
values without random state is [2, 9, 8, 1, 4]
values without random state is [5, 2, 8, 1, 9]
values without random state is [2, 8, 1, 5, 4]
values without random state is [4, 9, 5, 7, 8]


In [50]:
for i in range(5):
    x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.2,random_state=1)
    print("values with random state is",x1_train)

values with random state is [2, 1, 7, 5, 8]
values with random state is [2, 1, 7, 5, 8]
values with random state is [2, 1, 7, 5, 8]
values with random state is [2, 1, 7, 5, 8]
values with random state is [2, 1, 7, 5, 8]


In [51]:
#feature scaliing is used to vomit the outlayers


In [52]:
a=np.array([[1,2,3],[20,300,-40],[3,7,8]])

In [53]:
a

array([[  1,   2,   3],
       [ 20, 300, -40],
       [  3,   7,   8]])

In [54]:
from sklearn.preprocessing import StandardScaler
sc1=StandardScaler()#-0.7 to 1.3
b=sc1.fit_transform(a)

In [55]:
b

array([[-0.82116498, -0.72497582,  0.58789448],
       [ 1.4077114 ,  1.41406175, -1.40785256],
       [-0.58654642, -0.68908593,  0.81995808]])

In [56]:
x_train=sc1.fit_transform(x_train)

In [57]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [58]:
a.transpose()

array([[  1,  20,   3],
       [  2, 300,   7],
       [  3, -40,   8]])