In [1]:
import numpy as np

In [2]:
#Create an array of 10 zeros
a=np.zeros(10)

In [3]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#Create an array of 10 ones
b=np.ones(10)

In [5]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#Create an array of 10 fives
c=np.fives(10)

AttributeError: module 'numpy' has no attribute 'fives'

In [7]:
#Create an array of 10 fives
list=[5,5,5,5,5,5,5,5,5,5]
c=np.array(list)

In [8]:
c

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
c.ndim

1

In [10]:
a.ndim

1

In [11]:
b.ndim

1

In [12]:
b[3]

1.0

In [14]:
#Create an array of the integers from 10 to 50
c1=np.arange(10,51)

In [15]:
c1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
#Create an array of all the even integers from 10 to 50
d=np.arange(10,51,2)

In [17]:
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
#Create a 3x3 matrix with values ranging from 0 to 8
arr=[[0,1,2],[3,4,5],[6,7,8]]
e=np.array(arr)

In [20]:
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
#Create a 3x3 identity matrix
a=[1,1,1,1,1,1,1,1,1]
a.reshape[3,3]

AttributeError: 'list' object has no attribute 'reshape'

In [23]:
arr=np.array(a)

In [24]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
arr.reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
#Use NumPy to generate a random number between 0 and 1
g=np.random.rand()

In [39]:
g

0.09503431297144405

In [44]:
g1=np.random.rand(10)

In [45]:
g1

array([0.16720919, 0.96345731, 0.02722554, 0.26915147, 0.38130186,
       0.7960819 , 0.30600386, 0.29479262, 0.72072931, 0.89943994])

In [47]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal
#distribution
p=np.random.randint(10,20,25)

In [48]:
p

array([12, 12, 17, 13, 15, 13, 14, 19, 10, 15, 12, 11, 13, 12, 15, 13, 12,
       15, 19, 18, 19, 11, 15, 19, 13])

In [50]:
p=np.random.randint(5,10,25)

In [51]:
p

array([9, 7, 6, 9, 5, 9, 6, 5, 5, 8, 6, 6, 6, 9, 6, 5, 9, 7, 6, 7, 5, 8,
       9, 7, 6])

In [52]:
#Create the following matrix:
q=np.arange(0,16).reshape(4,4)

In [53]:
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
#Create an array of 20 linearly spaced points between 0 and 1:
lins=np.linspace(0,1,20)

In [56]:
lins

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [57]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [61]:
mat=np.arange(12,24).reshape(3,4)

array([[12, 13, 14, 15],
 [16, 17, 18, 19],
 [20,21,22, 23]])


In [62]:
mat

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
arr=[12,13,14,15,17,18,19,20,22,23,24,25]
matr=np.array(arr)

In [69]:
matr

array([12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25])

In [76]:
mat=matr.reshape(3,4)

In [77]:
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [71]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
#otput=20

In [75]:
matr

array([12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25])

In [78]:
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [79]:
mat[1,3]

20

In [80]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
mat[:,1]

array([ 2,  7, 12, 17, 22])

In [85]:
mat[4]

array([21, 22, 23, 24, 25])

In [87]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])